format = "$directory$git_branch$git_status$character"

[directory]
truncation_length = 3
style = "blue"

[git_branch]
symbol = ""
format = "[$symbol$branch]($style) "
style = "purple"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "yellow"

[character]
success_symbol = "[❯](bold green)"
error_symbol   = "[❯](bold red)"
